const facultyData = [
    {
        "department": "Computer Science and Engineering",
        "departmentCode": "computer_science",
        "faculty": [
            { "name": "Md. Hasibul Islam", "designation": "Head" },
            { "name": "Md. Rabiul Islam", "designation": "Advisory Dean" },
            { "name": "Md. Riaz Mahmud", "designation": "Assistant Professor" },
            { "name": "Md. Deloar Hossain", "designation": "Assistant Professor" },
            { "name": "Ferdib-Al-Islam", "designation": "Assistant Professor" },
            { "name": "Md. Tahmid Hasan", "designation": "Senior Lecturer" },
            { "name": "Md. Azizul Islam", "designation": "Senior Lecturer" },
            { "name": "Arjan Ghosh", "designation": "Senior Lecturer" },
            { "name": "Md. Hasibul Islam", "designation": "Senior Lecturer" },
            { "name": "Shahadat Hoshen Moz", "designation": "Senior Lecturer" },
            { "name": "Kazi Asif Ahmed", "designation": "Senior Lecturer" },
            { "name": "Md. Apu Hosen", "designation": "Senior Lecturer" },
            { "name": "Partha Protim Gharami", "designation": "Senior Lecturer" },
            { "name": "Md. Shamim Parvej", "designation": "Senior Lecturer" },
            { "name": "Md. Toufiqul Islam", "designation": "Senior Lecturer" },
            { "name": "Md. Nazim Uddin", "designation": "Senior Lecturer" },
            { "name": "Md. Abid Afsan Hamid", "designation": "Lecturer" },
            { "name": "Vashkar Kar", "designation": "Lecturer" },
            { "name": "Nuzhat Tabassum", "designation": "Lecturer" },
            { "name": "Talha Al Junaid", "designation": "Lecturer" },
            { "name": "Md. Mahadi Hasan", "designation": "Lecturer" },
            { "name": "Nazmus Sakib", "designation": "Lecturer" },
            { "name": "Md. Faizur Rahman", "designation": "Lecturer" },
            { "name": "Rashik Reza Fahim", "designation": "Lecturer" },
            { "name": "Md. Mossadek Touhid", "designation": "Lecturer" },
            { "name": "G.M. Mamun Al Imran", "designation": "Lecturer" },
            { "name": "Mst. Farjana Alam", "designation": "Lecturer" },
            { "name": "Shovon Mandal", "designation": "Lecturer" },
            { "name": "Aishwarja Paul Sourav", "designation": "Lecturer" },
            { "name": "Faria Afrin Tisha", "designation": "Lecturer" },
            { "name": "Susmita Sejuti Saha", "designation": "Lecturer" },
            { "name": "Ummay Habiba Mabsuma", "designation": "Lecturer" },
            { "name": "Md. Zahid Hassan Rabbi", "designation": "Lecturer" },
            { "name": "Md. Newaj Sorif Nishad", "designation": "Lecturer" },
            { "name": "Umme Habiba", "designation": "Lecturer" },
            { "name": "Debasish Biswas", "designation": "Lecturer" },
            { "name": "Faisal Habib Raim", "designation": "Lecturer" },
            { "name": "Pushpa Akhtar", "designation": "Lecturer" },
            { "name": "Md. Abdul Halim Khan", "designation": "Lecturer (C)" },
            { "name": "Saykat Mondal", "designation": "Lecturer (C)" },
            { "name": "Sujan Kumar Dhali", "designation": "Lecturer (C)" },
            { "name": "Mst. Dilruba Easmin", "designation": "Lecturer (C)" },
            { "name": "Md. Maharaj Kabir", "designation": "Lecturer" },
            { "name": "Md. Mahade Hasan", "designation": "Lecturer" },
            { "name": "Sima Roy", "designation": "Lecturer" },
            { "name": "Sadia Tasneem", "designation": "Associate Prof. & Head (GED)" },
            { "name": "Ferdousi Jahan Oyshi", "designation": "Senior Lecturer" },
            { "name": "Fatema Tuz Zohora Jui", "designation": "Lecturer (C)" },
            { "name": "Md. Touhiduzzaman Nishat", "designation": "Lecturer (C)" },
            { "name": "Dr. Md. Shah Alam", "designation": "Advisor (GED)" },
            { "name": "Arpita Azad", "designation": "Lecturer" },
            { "name": "Md. Ataullah", "designation": "Lecturer" },
            { "name": "Jalal Uddin Ahmed", "designation": "Professor & Dean (DBA)" },
            { "name": "Rejuana Sultana", "designation": "Senior Lecturer" },
            { "name": "Md. Arifuzzaman", "designation": "Senior Lecturer" },
            { "name": "Md. Vaskar Islam", "designation": "Lecturer" },
            { "name": "Fairuz Rahman", "designation": "Lecturer" }
        ]
    },
    {
        "department": "Civil Engineering",
        "departmentCode": "civil_engineering",
        "faculty": [
            { "name": "Prof. Dr. Kutub Uddin", "designation": "Professor & Dean" },
            { "name": "Tanvir Alam", "designation": "Senior Lecturer & Head" },
            { "name": "Md. Shahadat Hossain", "designation": "Senior Lecturer" },
            { "name": "Ashraful Islam", "designation": "Senior Lecturer" },
            { "name": "Chinmoy Mollik", "designation": "Lecturer" },
            { "name": "Chandan Dey", "designation": "Lecturer" },
            { "name": "Md. Masud Rana", "designation": "Lecturer (On Leave)" },
            { "name": "Md. Zihad Hossain", "designation": "Lecturer" },
            { "name": "Md. Abu Bakar Siddik Farhan", "designation": "Lecturer" },
            { "name": "Saumik Hasan Tanim", "designation": "Lecturer" },
            { "name": "Mehrabuzzaman", "designation": "Lecturer" },
            { "name": "G.M. Shahriar Hasib Sourav", "designation": "Lecturer" },
            { "name": "Md Bakhtiar Siddque", "designation": "Lecturer" },
            { "name": "Tanveer Tausif", "designation": "Lecturer" },
            { "name": "Md. Sakibul Islam", "designation": "Lecturer" },
            { "name": "Maliha Farjana", "designation": "Lecturer" },
            { "name": "Md. Shahadat Hossain", "designation": "Lecturer" },
            { "name": "Tashak", "designation": "Lecturer" }
        ]
    },
    {
        "department": "Electrical and Electronic Engineering",
        "departmentCode": "electrical_engineering",
        "faculty": [
            { "name": "Md. Sohel Rana", "designation": "Senior Lecturer & Head" },
            { "name": "Ifat Arin", "designation": "Assistant Professor" },
            { "name": "A.S.M. Tanvir Ul Islam", "designation": "Senior Lecturer" },
            { "name": "Sourav Pal", "designation": "Senior Lecturer" },
            { "name": "Imran Sardar", "designation": "Senior Lecturer" },
            { "name": "Md. Abu Salman", "designation": "Lecturer" },
            { "name": "Rakibul Islam", "designation": "Lecturer" },
            { "name": "Md. Harun Or Rasid", "designation": "Lecturer" },
            { "name": "Sunanda Das", "designation": "Lecturer" },
            { "name": "Gazi Md Nasim", "designation": "Lecturer" },
            { "name": "Abdullah Al Fahad", "designation": "Lecturer" },
            { "name": "Md. Maharaj Kabir", "designation": "Lecturer" }
        ]
    },
    {
        "department": "Architecture",
        "departmentCode": "architecture",
        "faculty": [
            { "name": "SM Zahed Sarwar", "designation": "Assistant Professor & Head" },
            { "name": "Dilshad Afroz", "designation": "Assistant Professor" },
            { "name": "Ishmat Ara", "designation": "Senior Lecturer" },
            { "name": "Fatama Siddique", "designation": "Senior Lecturer" },
            { "name": "Barnaly Roy", "designation": "Senior Lecturer" },
            { "name": "Hasibul Islam Bulbul", "designation": "Lecturer" },
            { "name": "Sayed Imtiaz Ahamed", "designation": "Lecturer" },
            { "name": "Sumaiya Khan Lubna", "designation": "Lecturer" },
            { "name": "Nipa Debnath", "designation": "Lecturer" },
            { "name": "Sheikh Md. Ali Reza", "designation": "Lecturer" },
            { "name": "Muhammad Golam Sami", "designation": "Lecturer" },
            { "name": "Adiat Rahman", "designation": "Lecturer" },
            { "name": "Shahnaz Parvin Eva", "designation": "Lecturer" },
            { "name": "Farhana Yasmin", "designation": "Lecturer" },
            { "name": "Md. Mohaiminul Islam", "designation": "Lecturer" },
            { "name": "Md. Sadi Murshed Bhuiyan", "designation": "Lecturer" },
            { "name": "Tousif-Ur Rahman", "designation": "Lecturer" },
            { "name": "Zerin Israt Emu", "designation": "Lecturer" }
        ]
    },
    {
        "department": "English",
        "departmentCode": "english",
        "faculty": [
            { "name": "Nafis Sadik Shamron", "designation": "Senior Lecturer and Head" },
            { "name": "Rabbi Biswas", "designation": "Lecturer" },
            { "name": "Jannatul Ferdous Asha", "designation": "Lecturer" },
            { "name": "Rifat Afrin Ritu", "designation": "Lecturer" },
            { "name": "Shabnur Ahmed Mimi", "designation": "Lecturer" },
            { "name": "Tanaj Kabir", "designation": "Lecturer" },
            { "name": "Fatmatuz Zohora Munmun", "designation": "Lecturer" },
            { "name": "Sanjida Afrose", "designation": "Lecturer" },
            { "name": "M Rad Shakil Ome", "designation": "Lecturer" },
            { "name": "Sima Roy", "designation": "Lecturer" },
            { "name": "F. M. Nowruzzaman Nion", "designation": "Lecturer" },
            { "name": "Sk. Md. Samsul Haque Rifad", "designation": "Lecturer" },
            { "name": "Sk. Al-Amin Hasan", "designation": "Lecturer" },
            { "name": "M. S. H. Saief", "designation": "Lecturer" },
            { "name": "Md. Shahriar Sharif", "designation": "Lecturer" },
            { "name": "Shamiha Rahman Prema", "designation": "Lecturer" }
        ]
    },
    {
        "department": "Journalism and Mass Communication",
        "departmentCode": "journalism",
        "faculty": [
            { "name": "Prof. Dr. Ashiquddin Mohammad Maruf", "designation": "Dean, Faculty of Arts Humanities & Social Sciences" },
            { "name": "Mustafizur Rahman", "designation": "Assistant Professor & Head" },
            { "name": "M M Mozahid Uddin", "designation": "Lecturer" },
            { "name": "Nazmul Huda", "designation": "Lecturer" },
            { "name": "Md. Ataullah", "designation": "Lecturer" },
            { "name": "Arpita Azad", "designation": "Lecturer" },
            { "name": "Umme Mohasina", "designation": "Lecturer" },
            { "name": "Samrat Shaikh", "designation": "Lecturer" }
         ]
    },
    {
        "department": "Business Administration",
        "departmentCode": "business_administration",
        "faculty": [
            { "name": "Prof. Jalal Uddin Ahmed", "designation": "Professor & Dean" },
            { "name": "Prof. Dr. Mia Abdur Rashid", "designation": "Professor & Head" },
            { "name": "Rumana Perveen", "designation": "Associate Professor (On Leave)" },
            { "name": "Md. Maruful Islam Rasel", "designation": "Assistant Professor" },
            { "name": "Md. Jahangir Alam", "designation": "Assistant Professor" },
            { "name": "Md Arif Hasan Khan", "designation": "Assistant Professor in Finance" },
            { "name": "Shaikh Golam Rakib", "designation": "Assistant Professor" },
            { "name": "Md. Ramjan Hossain", "designation": "Assistant Professor" },
            { "name": "Md. Arifuzzaman", "designation": "Senior Lecturer" },
            { "name": "Rejuana Sultana", "designation": "Senior Lecturer" },
            { "name": "Md. Vaskar Islam", "designation": "Lecturer" },
            { "name": "Waheda Islam", "designation": "Lecturer" },
            { "name": "Asaf-Ud-Daula", "designation": "Lecturer" },
            { "name": "Fairuz Rahman", "designation": "Lecturer" },
            { "name": "Shahanaz Sultana", "designation": "Lecturer" },
            { "name": "Syed Shamim Hasan", "designation": "Lecturer" },
            { "name": "Naznin Nahar Ome", "designation": "Lecturer" }
        ]
    },
    {
    "department": "Law (LLB)",
    "departmentCode": "law",
    "faculty": 
        [
            { "name": "Dr. Ashiquddin Md. Maruf", "designation": "Professor & Head" },
            { "name": "Md. Ramjan Hossain", "designation": "Assistant Professor" },
            { "name": "Md. Shadat Hossen", "designation": "Senior Lecturer" },
            { "name": "Ashraful Islam", "designation": "Senior Lecturer" },
            { "name": "Nazmul Huda", "designation": "Lecturer" },
            { "name": "Md. Ataullah", "designation": "Lecturer" },
            { "name": "Arpita Azad", "designation": "Lecturer" },
            { "name": "Farhana Yeasmin", "designation": "Associate Professor" }
        ]
    }
];
